### ISSUE TITLE
NuGet add too many frameworks

### ISSUE THREAD

**Issue by WikkidEdd** [microsoft/MixedReality-SceneUnderstanding-Samples#16]
If you just download, unzip and open this repo in Unity 2019.4.1 NuGet will download the packages but include frameworks that are not required for Unity in the project. 

![image](https://user-images.githubusercontent.com/1579290/92210405-f1ef9b00-ee8e-11ea-9615-b2bbd0eeb8ee.png)

This results in compile errors:

`PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Microsoft.MixedReality.SceneUnderstanding.DotNet.dll included or the current platform. Only one assembly with the same name is allowed per platform. `

### Repro steps
1. Download the repo via a zip file
2. Unzip
3. Open the project in unity 2019.4.1
4. Observe compile errors

### Workaround 
1. Create a new project
2. Copy assets folder from the repo into the new project
3. NuGet will correctly include only the required frameworks in the project.

### Addtional information
I haven't had chance to debug the exact cause of this, but it likely something odd related to the projects settings

I think this [issue ](https://github.com/microsoft/MixedReality-SceneUnderstanding-Samples/issues/15)about the instructions missing crucial steps is probably caused this problem. I think if this problem were solved, then the instructions would be adequate.

**Comment by jorgonz** [comment]
It seems that Nuget For Unity didn't kick in and selected the right libs.

The SU nuget has libs for different targets. Say, if you wanted to use SU in a native C# app using Dotnet, you would need a different lib. Nuget for Unity is there to handle this and avoid your project form having both assemblies in your project at the same time, Since Unity historically has had a problem with same name assemblies.


Can you help me understand the issue?

- Did you open the project using an up to date version of Unity Hub?
- Does the same thing happen to you with a 'git clone' copy of the project.
- Does the issue resolve itself if you close and open and project again?

I followed your repro steps, but i don't have the issues on my side. I'll investigate further.

**Comment by WikkidEdd** [comment]
Just to follow up. I just tried changing the path to "C:\Users\Edd\Downloads\MRSU\MRSU" and it worked. So definitely a path length issue with NuGetForUnity, not really your problem, but I have had a few complications now around excessive path lengths in the other Mixed Reality libraries. Perhaps consider less verbose project/library naming :)
