### ISSUE TITLE
OBJs saved by Scene Understanding SDK change coordinate system alignment when HoloLens moves

### ISSUE THREAD

**Issue by crystal-butler** [microsoft/MixedReality-SceneUnderstanding-Samples#26]
I am using a time series of scene object OBJs saved to the HoloLens 2 internal storage by the Scene Understanding example code for dynamically building maps of interior spaces. However, while the objects are aligned to one another when they are saved together, groups of objects from different calls to `SaveObjsToDiskAsync` have different orientations. Presumably this is due to the relative orientation of the headset; if the headset doesn't move, objects remain aligned. See screenshot below for a 3D visualization of two sets of (Wall, Floor, CompletelyInferred) objects created about 2 minutes apart in the same space.

![SU_updated_obj_sets_visualized](https://user-images.githubusercontent.com/1704599/144312753-6020537e-1b84-4684-9389-20d0a94e7cbb.png)

Is there a reason that having the saved OBJ orientation in 3D space aligned to the HoloLens rather than a fixed coordinate system is desirable? If this behavior is intended, is there any guidance on how to maintain object alignment when the HoloLens is moving? I am not displaying these objects in a Unity scene of any kind, but am automatically offloading the OBJs generated by `SaveObjsToDiskAsync` for processing and visual rendering on an external compute node. I would like to display a map that grows as the HoloLens wearer moves around but maintains a fixed position and orientation.

**Comment by jorgonz** [comment]
Hi Crystal,

My understanding is that this is by design, since a SU scene is aligned to an arbitrary anchor in the Hololens based on Head Tracking Data. @SzymonSPS will correct me if I'm wrong or elaborate if needed.

One solution that comes to my mind is to align all the geometry to an axis that you see fit before saving it to OBJ format, picking Unity's World Up vector and aligning all your geometry to that vector is very likely to solve the problem, similar to what we do when we show the scene in the Unity editor

Here's the code that we use to orient and visualize in editor, the difference here is that we would apply that rotation directly to the vertex data for the OBJ file
https://github.com/microsoft/MixedReality-SceneUnderstanding-Samples/blob/053a9bc40b8995700bdbba18f83b092de067d06f/Assets/SceneUnderstanding/Core/Understanding/Scripts/SceneUnderstandingManager.cs#L1438

I'll try to setup sometime this week to go over this and modify the save method to give you this behavior.

**Comment by crystal-butler** [comment]
@jorgonz I thought that function you linked to sounded promising, but wasn't sure whether adapting it to work when running SU on device was the right approach. If you're able to modify the save method as you say, that would be really helpful, thank you!

**Comment by SzymonSPS** [comment]
Hi Crystal-butler, sorry for seeing this so late. So yes, multiple calls to SU are never guaranteed to be using the same origin, this is also why you can't load these scenes "together" in the SDK because they are seperate. 

You really have 2 choices:

1. Ideally you can/should just make a 3d call of the whole space and save that. This is ideal for 2 reasons, 1. it will be aligned and consistent but 2. there is also no overlap from one point in time and the other.
2. Find a way to align them yourself. This is trickier, you could do some kind of topology or floorplan and try ICP or other methods to align the meshes, but it's not just the orientation, the position is also the problem.

Ideally SU would exist in a global and consistent world such that two calls at two different times were aligned with each other, this is just not possible at this point but we are thinkig about how to do this. I strongly encourage option #1 if it's possible.

**Comment by crystal-butler** [comment]
Thanks, @SzymonSPS; so you're saying that aligning to the Unity World Up vector as suggested by @jorgonz won't keep things aligned between calls to SU?

For your suggestion #1, I think you're referring to using the world mesh instead of scene objects--let me know if I've misunderstood. I had hoped to use scene objects rather than the world mesh mainly because the file sizes are much smaller: the communication channel I'm using to transmit the OBJs to an external compute node doesn't have much available bandwidth and the comms aren't under my control.

For 2, would be an option for me to scan a fiducial marker in the world to set an origin or alignment point, say at the beginning of a walk around an interior. I think that could solve the position problem, but not orientation. Any additional thoughts you have would be welcome.

**Comment by SzymonSPS** [comment]
For #1 you can still use Scene Objects, I just recommend doing one big call with a very large radius when you're ready. There really is no limit to how big a request you make, and you're guaranteed to get one nice big consistent world.

For #2 a fiducaial marker could work, if you use a QR code you could get orientation, but I'm still puzzled why #1 won't work, as making one big call at the end essentially does exactly what you want, it combines all of the data the device has and procduces one big reconstruction for you with everything aligned and consistent.

**Comment by crystal-butler** [comment]
@SzymonSPS I am getting all scene objects in one call with a large (100 meter) radius currently; as you say, scene objects in a single call align to one another just fine. The issue is that sequential SU calls do not return scene objects in the same orientation. I'm trying to display a map that changes and builds up over time as the HoloLens wearer walks around, so I need the geometry to remain aligned by position and orientation across SU calls so the map doesn't shift and rotate as the wearer moves. Hope that clarifies things and let me know if I'm misunderstanding what you're getting at.

As another thought, going back to @jorgonz original reply, if the scene objects are aligned to an arbitrary anchor based on head tracking, would it be possible to get head position at the time a set of scene objects is generated and use that to transform their orientations? Or would that approach not give consistent positioning across calls to SU either?

**Comment by crystal-butler** [comment]
After testing, it looks like the set of Scene Objects' origin and axis orientations are reliably based on the HoloLens pose at the time they're generated. I've been able to work with that assumption to transform them.
